import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";

const redHat = Red_Hat_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WebTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={cn("w-full", redHat.className)}>{children}</body>
    </html>
  );
}
